server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalog
    username: catalog
    password: catalog
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
