server:
  port: 8082

orders:
  clients:
    catalog:
      base-url: http://localhost:8081
    payments:
      base-url: http://localhost:8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orders
    username: orders
    password: orders
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
