server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/payments
    username: payments
    password: payments
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
