server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://catalog-service:8080
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
        - id: orders-service
          uri: http://orders-service:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
        - id: payments-service
          uri: http://payments-service:8080
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2
